### PR TITLE
Login form is styled, messages are added

### PR DESCRIPTION
**Pull request by josephwithay**

### CODE REVIEW

**Comment by kennethtran93** [comment]
Pull Latest Changes, Resolve, Commit/Push to same branch.

**Comment by kennethtran93** [comment]
I've commited your earlier PR branch, therefore, another team_repo pull, resolve, commit, push.

**Comment by josephwithay** [comment]
Pulled from team repo and it is merged now

**Comment by kennethtran93** [comment]
Do another Pull please

**Comment by kennethtran93** [comment]
Thank you.

**Pull request merged**
